[package]
name = "payment_account_deployer-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.payment_account_deployer]
path = ".."

[dependencies.elrond-wasm]
version = "0.15"

[dependencies.elrond-wasm-debug]
version = "0.15"
