[package]
name = "payment_processor-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.payment_processor]
path = ".."

[dependencies.elrond-wasm]
version = "0.15"

[dependencies.elrond-wasm-debug]
version = "0.15"
